version: '2'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8090:80
    environment:
      - PMA_HOST='${PMA_HOST}'
      - PMA_USER='${PMA_USER}'
      - PMA_PASSWORD='${PMA_PASSWORD}'
    volumes:
      - /sessions
