.catalog:
  name: "Rancher-phpMyAdmin"
  version: "v1.0.0"
  description: |
    Run phpMyAdmin for Rancher repo.
  questions:
    - variable: PMA_HOSTS
      label: "Host names of the MySQL servers"
      type: string
      required: false
    - variable: PMA_USER
      label: "MySQL User"
      type: string
      required: false
      description: "Set a MySQL User"
    - variable: PMA_PORT
      label: "Port of the MySQL server"
      type: int
      default: 3306
    - variable: PMA_PASSWORD
      label: "Password for MySQL User"
      type: password
      required: false
    - variable: WEB_PORT
      label: "Web interface port phpMyAdmin"
      type: int
      default: 9090
      required: false
    - variable: PMA_ARBITRARY
      label: "When set to connection to the arbitrary server will be allowed"
      type: boolean
      required: true
      default: true
    - variable: PMA_VERBOSES
      label: "Separated list of verbose names of the MySQL servers"
      type: string
      required: false
    - variable: PMA_ABSOLUTE_URI
      label: "User-facing URI"
      type: string
      required: false

version: '2'
services:
  phpmyadmin:
    scale: 1
    start_on_create: true
    retain_ip: true
